services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  backend:
    image: unahur/lab-backend
    build:
      context: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - URI_MONGO=mongodb://admin:password@mongodb/

# Define named volumes
volumes:
  mongo-data:
    driver: local