services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_URL:  mongodb://admin:password@mongodb/
      # ME_CONFIG_MONGODB_URL: mongodb+srv://Desa2023G2:8Jg8tX6GPmtIuBRG@cluster0.dr6vbh4.mongodb.net/
    depends_on:
      mongodb:
        condition: service_started
  backend:
    image: unahur/lab-backend
    build:
      context: .
    restart: unless-stopped
    ports:
      - "3002:8080"
    environment:
      URI_MONGO: mongodb://admin:password@mongodb/Laboratorio
      PORT: 8080
      ORIGIN1: http://lab-api.localdev.me:3001
      ORIGIN2: http://lab-front.localdev.me:3000
    depends_on:
      mongodb:
        condition: service_started
  front:
    image: unahur/lab-front
    build:
      context: ../appLabFront
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://lab-api.localdev.me:3002
    depends_on:
      - backend

volumes:
  mongo-data:
    driver: local